/**
 * Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
 * 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
 * By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
 */
function problem2() {
	var n = 0;
	var value = 0;
	var sum = 0;
	while (value < 4000000) {
		value = fib(n);
		if (value % 2 === 0) { sum += value; }
		n++;
	}

	return sum;
}